config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, except: %i[edit update destroy] do
    resources :doses, only: %i[new create]
    collection do
      get :searched
    end
  end
  resources :doses, only: :destroy

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient, message: 'Every ingredient should be only once in the cocktail' }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update]
  def index
    @cocktails = Cocktail.all
  end

  def show; end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def searched
    @cocktails = Cocktail.where('name ILIKE ?', "#{search_params['query']}%")
    if @cocktails.empty?
      render 'searched'
    else
      render 'index'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def search_params
    params.require(:search).permit(:query)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, except: :destroy

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/cocktails/_navbar.html.erb
<nav class="d-flex fixed-top" id="custom-navbar"=>
  <ul class="list-group list-group-horizontal flex-grow-1">
    <li class="custom-list" id="custom-navbar">
      <%= link_to "Home", root_path %>
    </li>
    <li class="custom-list" id="custom-navbar">
      <%= link_to "See all cocktails", cocktails_path %>
    </li>
  </ul>
  <ul class="list-group list-group-horizontal">
    <li class="custom-list" id="custom-navbar">
      <%= link_to "Add a Cocktail", new_cocktail_path %>
    </li>
  </ul>
</nav>

app/views/cocktails/_navbar_white.html.erb
<nav class="d-flex fixed-top" id="custom-navbar"=>
  <ul class="list-group list-group-horizontal flex-grow-1">
    <li class="custom-list" id="custom-navbar">
      <%= link_to "Home", root_path, id: "white" %>
    </li>
    <li class="custom-list" id="custom-navbar">
      <%= link_to "See all cocktails", cocktails_path, id: "white" %>
    </li>
  </ul>
  <ul class="list-group list-group-horizontal">
    <li class="custom-list" id="custom-navbar">
      <%= link_to "Add a Cocktail", new_cocktail_path, id: "white" %>
    </li>
  </ul>
</nav>

app/views/cocktails/_searchbar.html.erb
<div class="searchbar-postion">
  <%= simple_form_for :search, url: searched_cocktails_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Search for a cocktail" />
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<%= render 'navbar' %>
<div style="margin-top: 7vh">
  <%= render 'searchbar' %>
</div>
  <div class="container" style="margin-top: 5vh">
    <div class="row">
    <% @cocktails.each do |e| %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 py-3">
        <%= link_to cocktail_path(e), id: "change-textdecoration" do%>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path e.photo.key, height: 300, width: 400, crop: :fill %>')">
            <%= e.name %>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= render 'navbar' %>
<h1>Add a new cocktail</h1>
<%= render 'form' %>

app/views/cocktails/searched.html.erb
<%= render 'navbar' %>
<div class="container" style="padding: 7vh">
  <%= render 'searchbar' %>
  <div class="custom-container">
    <h1 class="">0 entries found</h1>
    <i class="fas fa-search icon-size-color"></i>
  </div>
</div>

app/views/cocktails/show.html.erb
<%= render 'navbar_white' %>
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, crop: :fill %>')">
  <%= render 'searchbar' %>
</div>

<div class="ingredients-container">
  <h1><%= @cocktail.name %></h1>
  <% @cocktail.doses.each do |e| %>
    <%= "#{e.description} | #{e.ingredient.name}" %>
    <%= link_to "Delete", dose_path(e), method: :delete  %>
    <br>
  <% end %>

  <%= link_to "Go back", cocktails_path %>

  <%= link_to "Add Ingredient", new_cocktail_dose_path(@cocktail)%>

</div>

app/views/doses/new.html.erb
<h1>Add a new Ingredient</h1>

<%= simple_form_for [@cocktail,@dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_navbar.html.erb
<nav class="d-flex fixed-top" id="custom-navbar"=>
  <ul class="list-group list-group-horizontal flex-grow-1">
    <li class="custom-list" id="custom-navbar">
      <%= link_to "Home", root_path, id: "white" %>
    </li>
    <li class="custom-list" id="custom-navbar">
      <%= link_to "See all cocktails", cocktails_path, id: "white" %>
    </li>
  </ul>
  <ul class="list-group list-group-horizontal">
    <li class="custom-list" id="custom-navbar">
      <%= link_to "Add a Cocktail", new_cocktail_path, id: "white" %>
    </li>
  </ul>
</nav>

app/views/pages/_searchbar.html.erb
<div class="searchbar-postion">
  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" id="search_query banner-typed-text"/>
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<%= render 'navbar' %>
<div class="home-banner">
  <%= render 'searchbar' %>
</div>